export const IPC_CHANNELS = {
  templatesList: "md2word:templates:list",
  templatesAdd: "md2word:templates:add",
  templatesUpdate: "md2word:templates:update",
  templatesRemove: "md2word:templates:remove",
  templatesSetDefault: "md2word:templates:set-default",
  templatesValidate: "md2word:templates:validate",
  templatesValidateDraft: "md2word:templates:validate-draft",
  filesPickMarkdown: "md2word:files:pick-markdown",
  filesRegisterMarkdownPath: "md2word:files:register-markdown-path",
  filesPickTemplateDocx: "md2word:files:pick-template-docx",
  filesPickCss: "md2word:files:pick-css",
  filesPickOutput: "md2word:files:pick-output",
  conversionsStart: "md2word:conversions:start",
  conversionsCancel: "md2word:conversions:cancel",
  conversionsEvent: "md2word:conversions:event",
  environmentCheck: "md2word:environment:check",
  capabilitiesDescribe: "md2word:capabilities:describe",
  shellOpenOutput: "md2word:shell:open-output",
  shellRevealOutput: "md2word:shell:reveal-output",
  shellOpenTemplateLibrary: "md2word:shell:open-template-library",
} as const;
